/* SPDX-License-Identifier: GPL-2.0-or-later */

#pragma once

#define VIAL_KEYBOARD_UID {0x65, 0x9A, 0x6E, 0x3C, 0x47, 0x63, 0xB9, 0x9B}

#define VIAL_UNLOCK_COMBO_ROWS { 3, 0 }
#define VIAL_UNLOCK_COMBO_COLS { 0, 3 }

#define STM32_ONBOARD_EEPROM_SIZE 8192
#define DYNAMIC_KEYMAP_LAYER_COUNT 12
#define DYNAMIC_KEYMAP_MACRO_COUNT 36

#define COMBO_MUST_PRESS_IN_ORDER
#define VIAL_COMBO_ENTRIES 12
/*#define DYNAMIC_KEYMAP_MACRO_EEPROM_SIZE 1280 */